[package]
name = "LynxVk"
version = "0.1.0"
edition = "2024"

# [workspace]
# members = ["src/teapot", "src/vulkan_base"]

[dependencies]
log = "0.4.27"
simplelog = "0.12.2"
mess = { path = "src/mess" }
teapot = { path = "src/teapot" }
vulkan_base = { path = "src/vulkan_base" }
